import type { ProfileConfig } from './types.ts';

/** Starting points the builder UI clones — never mutate one in place. */
export const presets: Record<'mert' | 'stopa' | 'minimal', ProfileConfig> = {
  mert: {
    allowAppStore: true,
    allowPrivateBrowsing: true,
    autoFilterAdult: false,
    blockedApps: [
      { bundleId: 'com.atebits.Tweetie2', name: 'X' },
      { bundleId: 'com.burbn.instagram', name: 'Instagram' },
      { bundleId: 'com.burbn.barcelona', name: 'Threads' },
      { bundleId: 'com.zhiliaoapp.musically', name: 'TikTok' },
      { bundleId: 'com.google.ios.youtube', name: 'YouTube' },
      { bundleId: 'com.reddit.Reddit', name: 'Reddit' },
      { bundleId: 'com.facebook.Facebook', name: 'Facebook' },
      { bundleId: 'com.netflix.Netflix', name: 'Netflix' },
      { bundleId: 'tv.twitch', name: 'Twitch' },
      { bundleId: 'com.linkedin.LinkedIn', name: 'LinkedIn' },
      { bundleId: 'pinterest', name: 'Pinterest' },
      { bundleId: 'com.amazon.aiv.AIVApp', name: 'Prime Video' },
    ],
    displayName: 'Dumbphone',
    identifier: 'com.example.dumbphone',
    lockRemoval: true,
    organization: 'Me',
    webFilter: {
      deniedUrls: [
        'https://x.com',
        'https://twitter.com',
        'https://www.youtube.com',
        'https://m.youtube.com',
        'https://youtu.be',
        'https://instagram.com',
        'https://threads.net',
        'https://www.threads.com',
        'https://tiktok.com',
        'https://facebook.com',
        'https://reddit.com',
        'https://twitch.tv',
        'https://netflix.com',
        'https://primevideo.com',
        'https://linkedin.com',
        'https://pinterest.com',
      ],
      mode: 'deny',
      // Sign-in for YouTube on other devices still has to resolve.
      permittedUrls: ['https://accounts.youtube.com'],
    },
  },
  minimal: {
    allowAppStore: true,
    allowPrivateBrowsing: true,
    autoFilterAdult: false,
    blockedApps: [],
    displayName: 'Dumbphone',
    identifier: 'com.example.dumbphone',
    lockRemoval: false,
    organization: 'Me',
    webFilter: { mode: 'off' },
  },
  stopa: {
    allowAppStore: false,
    allowPrivateBrowsing: true,
    autoFilterAdult: false,
    blockedApps: [],
    displayName: 'Dumbphone',
    identifier: 'com.example.dumbphone',
    lockRemoval: true,
    organization: 'Me',
    webFilter: {
      allowedUrls: [
        'https://maps.google.com',
        'https://mail.google.com',
        'https://calendar.google.com',
        'https://chatgpt.com',
        'https://claude.ai',
        'https://wikipedia.org',
      ],
      mode: 'allow',
    },
  },
};
