#!/usr/bin/env python3
"""Build the standalone file that install.sh downloads.

Run this before a release:

    python3 cli/build_single.py

It writes cli/dist/supervise: the package module with a shebang on top and the
executable bit set. The module is standard library only, so the one file runs
as it is. The version comes along with the source.
"""

import stat
from pathlib import Path

CLI_ROOT = Path(__file__).resolve().parent
SOURCE = CLI_ROOT / "src" / "supervise_iphone" / "cli.py"
TARGET = CLI_ROOT / "dist" / "supervise"
SHEBANG = "#!/usr/bin/env python3\n"
BANNER = (
    "# Generated by cli/build_single.py from cli/src/supervise_iphone/cli.py.\n"
    "# Do not edit this file. Edit the package, then build again.\n"
)
EXECUTABLE = stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH


def build(target: Path = TARGET) -> Path:
    """Write the single file and return its path."""
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(SHEBANG + BANNER + SOURCE.read_text())
    target.chmod(target.stat().st_mode | EXECUTABLE)
    return target


if __name__ == "__main__":
    print(f"Wrote {build()}")
